# Generated by Django 4.1 on 2022-08-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_created_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "title",
                    "description",
                    "brand",
                    "sku",
                    "category",
                    "price",
                    "image",
                ]
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="purchase_price",
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial_quantity", models.IntegerField()),
                ("purchase_price", models.FloatField()),
                ("remaning_quantity", models.IntegerField()),
                ("profit_margin", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Product_Inventory",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "product",
                    "initial_quantity",
                    "remaning_quantity",
                    "purchase_price",
                    "profit_margin",
                    "updated_at",
                ],
            },
        ),
    ]
